image: Visual Studio 2022
version: '#{build}'
clone_depth: 1
environment:
  NUGET_API_KEY:
    secure: WkoebXl/PywsjkXpssKTZLndjn1sie9o6Rarisx5dtSHDnNTQCbQNf/xPE/2meGO
  GITHUB_PAT:
    secure: h1tLqkBt5SP2X/gyu9+SE5hjkmBvldDcPiMsNgwjDfKFqh++aLZMbPZrFytrX2YJ
install:
  - pwsh: dotnet new tool-manifest
  - pwsh: dotnet tool install Cake.Tool --version 2.1.0
skip_commits:
  files:
    - ./.gitignore
    - ./.editorconfig
    - ./LICENSE
    - ./README.md
build_script:
  - cmd: dotnet cake ./build.cake
test: false # build script will run all the tests automatically
deploy: false
